
go.property("speed", 0)
go.property("jumpTime",0)
go.property("jumpForce", 0)
go.property("gravity", 0)

go.property("twirlForce", 0)
go.property("poundForce", 0)

go.property("speedupTime", 0)
go.property("speedFaster", 0)


function init(self)
	msg.post("#", "acquire_input_focus")
	
	self.move_dir = 0
	self.velocity = vmath.vector3()
	self.grounded = false
	self.correction = vmath.vector3()
end

function update(self, dt)

	--horizontal
	self.velocity.x = self.input_x * self.speed

	local pos = go.get_position()
	pos = pos + self.velocity * dt
	go.set_position(pos)
	
end

function late_update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)	
	--hezcejc
	if action_id == hash("right") then
		if action.pressed then
			self.input_x = 1
		elseif action.released and self.input_x == 1 then
			self.input_x = 0
		end

	elseif action_id == hash("left") then
		if action.pressed then
			self.input_x = -1
		elseif action.released and self.input_x == -1 then
			self.input_x = 0
		end
	end
end

function on_reload(self)
end
