local m_run = require "scripts.player.moveset.m_run"
local m_jump = require "scripts.player.moveset.m_jump"
local m_idle = require "scripts.player.moveset.m_idle"
local m_twirl = require "scripts.player.moveset.m_twirl"

local c_idle = require "scripts.player.moveset.c_idle"
local c_attack = require "scripts.player.moveset.c_attack"
local c_leap = require "scripts.player.moveset.c_leap"

go.property("speed", 0)
go.property("jumpTime",0)
go.property("jumpForce", 0)
go.property("gravity", 0)

go.property("twirlForce", 0)
go.property("poundForce", 0)

go.property("speedupTime", 0)
go.property("speedFaster", 0)


function init(self)
	msg.post("#", "acquire_input_focus")

	--stavovy objekt!!!!
	self.stateVars = {
		speed = self.speed,
		gravity = self.gravity,
		jumpForce = self.jumpForce,
		velocity = vmath.vector3(),
		----fixyxxxxxnoutt tady ma byt false a proper check!!
		isGrounded = true,
		dirKeys = {left = false, right = false},
		isAttacking = false
	}
	
	self.movStates = {m_idle = m_idle, m_run = m_run, m_jump = m_jump, m_twirl = m_twirl}
	self.currentMov = "m_idle"
	self.movStates[self.currentMov].enter(self.stateVars)

	self.combatStates = {c_idle = c_idle, c_attack = c_attack, c_leap = c_leap}
	self.currentCombat = "c_idle"
	self.combatStates[self.currentCombat].enter(self.stateVars)

	--prepinani stavu OOOOOO
	self.switchAPI = {
		changeMovement = function(newState)
			if self.currentMov ~= newState and self.movStates[newState] then
				self.movStates[self.currentMov].exit(self.stateVars)
				self.currentMov = newState
				self.movStates[self.currentMov].enter(self.stateVars)
			end
		end,
		changeCombat = function(newState)
			if self.currentCombat ~= newState and self.combatStates[newState] then
				self.combatStates[self.currentCombat].exit(self.stateVars)
				self.currentCombat = newState
				self.combatStates[self.currentCombat].enter(self.stateVars)
			end
		end

	}

	
end

function update(self, dt)
	self.movStates[self.currentMov].update(self.stateVars, dt, self.switchAPI)
	self.combatStates[self.currentCombat].update(self.stateVars, dt, self.switchAPI)

	--pohyb do stran (META skrznaskrz)
	local pos = go.get_position()
	pos = pos + self.stateVars.velocity * dt
	go.set_position(pos)

	--fixxxxx nezakomentovavat po kontorle zeme "!!!!
	--self.stateVars.isGrounded = false
end

function on_input(self, action_id, action)
	self.movStates[self.currentMov].handle_input(self.stateVars, action_id, action, self.switchAPI)
	self.combatStates[self.currentCombat].handle_input(self.stateVars, action_id, action, self.switchAPI)
end
